feat: send tokens
devtronghieu/berry-wallet pull request #8
Opened 2024-05-01 14:19 UTC by Fbin243

2024-05-01 15:05 UTC, devtronghieu commented on src/screens/Home/index.tsx
> +            }}
make it `onClick(() => setModalIsOpen(true))`

2024-05-01 15:06 UTC, devtronghieu commented on src/screens/Send/Select.tsx
> +  data: Token[];
`data` to `tokens`

2024-05-04 08:18 UTC, devtronghieu commented on src/state/index.ts
> +  transactionFees?: number[];
I think we won't want to store fee as a state, we will fetch the state everytime user wants to make a transaction instead (because fee should be a real-time value)

2024-05-04 08:49 UTC, ltminhthu requested changes

2024-05-04 08:49 UTC, ltminhthu commented on src/screens/BottomSheet.tsx
> +              <div onClick={onClose} className="cursor-pointer">
`onClick` should be place in `button` instead of `div`

2024-05-04 08:49 UTC, ltminhthu commented on src/screens/BottomSheet.tsx
> +      <Sheet.Container>
I think there is a `Sheet.Header`, you can use it to container `title` and `closeBtn`

2024-05-04 08:49 UTC, ltminhthu commented on src/screens/BottomSheet.tsx
> +          <div className="px-5 py-4 bg-primary-100 rounded-t-3xl">
there should a `gap` here and I also prefer a `fixed height` (572px) for the bottom sheet because there's no need to make it responsive

2024-05-04 08:49 UTC, ltminhthu commented on src/screens/BottomSheet.tsx
> +import CloseSquareIcon from "@/icons/CloseSquare";
change it to `import { CloseSquareIcon } from '@/icons/index'`

2024-05-04 08:49 UTC, ltminhthu commented on src/screens/Home/index.tsx
> +            Icon={SendIcon}
remove space here

2024-05-04 08:49 UTC, ltminhthu commented on src/screens/Home/index.tsx
> +            onClick={() => {
combine all these to a function called `handleOnSendClick`

2024-05-04 08:49 UTC, ltminhthu commented on src/screens/Home/index.tsx
> +            onClick={() => {
same as above

2024-05-04 08:49 UTC, ltminhthu commented on src/screens/Home/index.tsx
> +  const CurrentBottomSheetChildren = BottomSheetChidren[BottomSheetType];
this should be in a `useMemo` with dependency is `[BottomSheetType]`

2024-05-04 08:49 UTC, ltminhthu commented on src/screens/Home/index.tsx
> +  const BottomSheetChidren: Record<string, React.ElementType> = {
I recommend you put these things in the `BottomSheet` component and manage it all in that component (this is optional)

2024-05-04 08:49 UTC, ltminhthu commented on src/components/TokenList.tsx
> +  console.log("TokenList: ", tokens);
remove log here

2024-05-04 08:49 UTC, ltminhthu commented on src/components/TokenList.tsx
> +        console.log(token);
same as above

2024-05-04 08:49 UTC, ltminhthu commented on src/screens/Send/Select.tsx
> +import { Token } from "@engine/types";
move this file to `@components`

2024-05-04 08:49 UTC, ltminhthu commented on src/screens/Send/Select.tsx
> +  selectedIndex: number;
change it to `selecteditemIndex`

2024-05-04 08:49 UTC, ltminhthu commented on src/screens/Send/Select.tsx
> +  onSelectedIndex: (index: number) => void;
change it to `onSelectItem`

2024-05-04 08:49 UTC, ltminhthu commented on src/screens/Send/Select.tsx
> +  tokens: Token[];
I think it should not be `Token[]`, can you make it more generic to use for `NFT` and other stuff. We just call it `items`

2024-05-04 08:49 UTC, ltminhthu commented on src/screens/Send/Select.tsx
> +            <div key={token.mint} className="select-option" onClick={() => handleSelectOption(index)}>
according to the ui design, there is a `hovered style` here, wish you can add

2024-05-04 08:49 UTC, ltminhthu commented on src/screens/Send/Select.tsx
> +              {index === selectedIndex ? <TickSquareIcon size={20} /> : null}
you can change it to `{index === selectedIndex && <TickSquareIcon size={20} />}`

2024-05-04 08:49 UTC, ltminhthu commented on src/screens/Send/index.tsx
> +  const isValidTransaction = isValidPublicKey && isValidAmount;
I think, we should combine all state of a transaction to a big state called `transactionContext` and put it in `valtio`

2024-05-04 08:49 UTC, ltminhthu commented on src/screens/Send/index.tsx
> +      const rawTransaction = transaction.serialize();
you should put these things into the `@engine/transactions/send/*`

2024-05-04 08:52 UTC, Fbin243 commented on src/state/index.ts
> +  transactionFees?: number[];
I forgot removing it

2024-05-04 09:08 UTC, Fbin243 commented on src/screens/BottomSheet.tsx
> +          <div className="px-5 py-4 bg-primary-100 rounded-t-3xl">
you mean the gap between Sheet.Header and Sheet.Content?

2024-05-04 09:15 UTC, Fbin243 commented on src/screens/Home/index.tsx
> +            Icon={SendIcon}
The Prettier format my code like that :( This component receives a lot of props, so I think displaying it vertically looks better.

`<FeatureButton
      Icon={WalletIcon}
      title="Receive"
      onClick={() => {
        setBottomSheetType("Receive");
        setModalIsOpen(true);
      }}
    />`

2024-05-04 09:23 UTC, Fbin243 commented on src/screens/Send/Select.tsx
> +  tokens: Token[];
yeah, in the previous commit, I named it data instead of tokens :)

2024-05-04 09:26 UTC, Fbin243 commented on src/screens/Send/Select.tsx
> +            <div key={token.mint} className="select-option" onClick={() => handleSelectOption(index)}>
I have added it in css instead

2024-05-04 09:48 UTC, Fbin243 commented on src/screens/Send/Select.tsx
> +import { Token } from "@engine/types";
That's not my file. I can't move it to the @component :(

2024-05-06 15:36 UTC, Fbin243 commented on src/screens/Send/index.tsx
> +    isValidPublicKey,
Yeah, I have realized that problem and solve it by returning it back to the FC with useState()

2024-05-06 16:33 UTC, Fbin243 commented on src/engine/transactions/send/index.ts
> +    const signature = nacl.sign.detached(transactionBuffer, senderSerkey);
[https://solana.com/docs/clients/javascript-reference#example-usage](url)

2024-05-07 03:23 UTC, devtronghieu commented on src/components/TokenList.tsx
> +import { formatCurrency,getLocalLogo } from "@utils/general";
please add a space here `{ formatCurrency, getLocalLogo }`

2024-05-07 05:14 UTC, ltminhthu commented on src/screens/Send/index.tsx
> +  };
create utils file and create these function inside it, call function `validatePublicKey`, `validateBalance`, etc.

2024-05-07 05:14 UTC, ltminhthu commented on src/state/transaction.ts
> +  setItem: (item: Token) => {
`setToken`

2024-05-07 05:17 UTC, Fbin243 commented on src/engine/transaction/send/index.ts
> +export const getTransactionBySignature = async (signature: TransactionSignature) => {
I use it for getting the date of transaction

2024-05-07 05:35 UTC, ltminhthu commented on src/engine/transaction/send/index.ts
> +export const getTransactionBySignature = async (signature: TransactionSignature) => {
you don't need it, date should be set at the time you construct transaction (or when the user click "Continue"

2024-05-07 05:35 UTC, ltminhthu commented on src/engine/transaction/send/index.ts
> +    const transactionInfo = await getTransactionBySignature(signature);
instead of requesting for a transaction, you can only check the signature is valid and then set the status to success, it's more ez and clear to understand

2024-05-07 05:41 UTC, ltminhthu commented on src/engine/utils.ts
> +}
you can use it like this: 

`export const convertDateToReadable = (date) =>
	date.toLocaleDateString('en-US', {
		year: 'numeric',
		month: 'long',
		day: 'numeric',
	});`

2024-05-07 10:01 UTC, devtronghieu approved these changes

2024-05-07 10:01 UTC, merged